### PR TITLE
Download path not found

### PR DESCRIPTION
**Pull request by AndersTao**
I was unable to get use this recipe without these changes

- Updated URL to the download path
- Added wildcards to names
- Removed URLTextSearcher processor

### CODE REVIEW

**Comment by foigus** [comment]
Correct me if I'm wrong, but doesn't `http://downloads.ecamm.com/CallRecorder.zip` download the Call Recorder Demo? The goal of this recipe is to download a licensed copy from someone's Ecamm customer center.

**Comment by AndersTao** [comment]
You are correct, do you do some kind of pre-login to get access to the licens site?

**Comment by foigus** [comment]
See:

https://github.com/autopkg/foigus-recipes/blob/master/Ecamm/CallRecorderforSkype.download.recipe#L8

and

https://github.com/autopkg/foigus-recipes/blob/master/Ecamm/CallRecorderforSkype.download.recipe#L15-L16

In short, knowing the URL to someone's Ecamm Customer Center allows downloading the licensed version.

**Comment by AndersTao** [comment]
D'oh!

**Comment by foigus** [comment]
Did the recipe work for you once the Ecamm Customer Center URL was supplied?

**Comment by AndersTao** [comment]
Sorry, no!
My customer don't own a licens, I just wanted to add the app, to inspire users to buy the software 😊

**Comment by foigus** [comment]
Closing this PR since I intended this recipe to download a licensed copy of CallRecorder for Skype.

**Pull request closed without merging**
